runner:
  total_steps: 30000
  gradient_clipping: 1
  gradient_accumulate_steps: 4

  log_step: 500
  eval_step: 1000
  save_step: 1000
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 1400

downstream_expert:
  datarc:
    root: ./data/superb_all/1.2_resampled/
    train: ./data/superb_all/er_train_0.1/train.txt
    dev: ./data/superb_all/er_train_0.1/dev.txt
    test: ./data/superb_all/er_train_0.1/test.txt
    train_batch_size: 8
    eval_batch_size: 8
    num_workers: 8

  modelrc:
    projector_dim: 256
    select: UtteranceLevel

    UtteranceLevel:
      pooling: MeanPooling
