runner:
  total_steps: 5000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 50
  eval_step: 50
  save_step: 50
  max_keep: 1
  train_dataloader: lxt_train
  eval_dataloaders: 
    - lxt_dev
    - lxt_test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 5000

downstream_expert: 
  datarc:
    lxt_audio: data/superb_all/1.1_distributed/audio
    lxt_train: data/superb_all/sid_train_5/train.txt
    lxt_dev: data/superb_all/sid_train_5/dev.txt
    lxt_test: data/superb_all/sid_train_5/test.txt

    train_batch_size: 32
    num_workers: 12

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
