runner:
  total_steps: 1000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 100
  eval_step: 100
  save_step: 100
  max_keep: 1
  train_dataloader: train
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# # comment the whole scheduler config block to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 5000

downstream_expert: 
  datarc:
    lxt_audio: data/superb_all/1.1_distributed/audio
    split_dir: data/superb_all/sid_train_5
    min_secs: 1
    max_secs: 2
    vad: true

    train_batch_size: 32
    num_workers: 12

  modelrc:
    projector_dim: 0
    select: FrameLevel
